<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class ActivateSubscriptionNamespaceRequest
{
    /**
     * The namespace name
     *
     * @var string $namespaceName
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=namespaceName')]
    public string $namespaceName;

    /**
     * The existing subscription ID
     *
     * @var string $subscriptionID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriptionID')]
    public string $subscriptionID;

    /**
     * @param  string  $namespaceName
     * @param  string  $subscriptionID
     * @phpstan-pure
     */
    public function __construct(string $namespaceName, string $subscriptionID)
    {
        $this->namespaceName = $namespaceName;
        $this->subscriptionID = $subscriptionID;
    }
}