<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;


class CreateSchemaStoreItemRequestBody
{
    /**
     * The format of the OpenAPI specification.
     *
     * @var Format $format
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('format')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Operations\Format')]
    public Format $format;

    /**
     * The package name to use in code snippets / quickstart.
     *
     * @var string $packageName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('packageName')]
    public string $packageName;

    /**
     * The classname of the SDK to use in code snippets / quickstart.
     *
     * @var string $sdkClassname
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sdkClassname')]
    public string $sdkClassname;

    /**
     * The OpenAPI specification to store.
     *
     * @var string $spec
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('spec')]
    public string $spec;

    /**
     * @param  Format  $format
     * @param  string  $packageName
     * @param  string  $sdkClassname
     * @param  string  $spec
     * @phpstan-pure
     */
    public function __construct(Format $format, string $packageName, string $sdkClassname, string $spec)
    {
        $this->format = $format;
        $this->packageName = $packageName;
        $this->sdkClassname = $sdkClassname;
        $this->spec = $spec;
    }
}