<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Models\Shared;
use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class CreateSubscriptionRequest
{
    /**
     * The subscription to create
     *
     * @var Shared\RegistrySubscription $registrySubscription
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Shared\RegistrySubscription $registrySubscription;

    /**
     * The workspace ID
     *
     * @var string $workspaceId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workspace_id')]
    public string $workspaceId;

    /**
     * @param  Shared\RegistrySubscription  $registrySubscription
     * @param  string  $workspaceId
     */
    public function __construct(Shared\RegistrySubscription $registrySubscription, string $workspaceId)
    {
        $this->registrySubscription = $registrySubscription;
        $this->workspaceId = $workspaceId;
    }
}