<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Models\Shared;
/** GenerateCodeSamplePreviewAsyncResponseBody - Job accepted, returns a job ID to poll for status and result */
class GenerateCodeSamplePreviewAsyncResponseBody
{
    /**
     * The job ID for polling
     *
     * @var string $jobId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job_id')]
    public string $jobId;

    /**
     * The current status of the job. Possible values are `pending` or `running`.
     *
     * @var Shared\CodeSamplesJobStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\CodeSamplesJobStatus')]
    public Shared\CodeSamplesJobStatus $status;

    /**
     * @param  string  $jobId
     * @param  Shared\CodeSamplesJobStatus  $status
     * @phpstan-pure
     */
    public function __construct(string $jobId, Shared\CodeSamplesJobStatus $status)
    {
        $this->jobId = $jobId;
        $this->status = $status;
    }
}