<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetActionRequest
{
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=org')]
    public string $org;

    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=repo')]
    public string $repo;

    /**
     * The targetName of the workflow target.
     *
     * @var ?string $targetName
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=targetName')]
    public ?string $targetName = null;

    public function __construct()
    {
        $this->org = '';
        $this->repo = '';
        $this->targetName = null;
    }
}