<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetCodeSamplesRequest
{
    /**
     * The registry URL from which to retrieve the snippets. E.g. https://spec.speakeasy.com/org/ws/my-source
     *
     * @var string $registryUrl
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=registry_url')]
    public string $registryUrl;

    /**
     * $languages
     *
     * @var ?array<string> $languages
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=languages')]
    public ?array $languages = null;

    /**
     * $operationIds
     *
     * @var ?array<string> $operationIds
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=operation_ids')]
    public ?array $operationIds = null;

    /**
     * @param  string  $registryUrl
     * @param  ?array<string>  $languages
     * @param  ?array<string>  $operationIds
     */
    public function __construct(string $registryUrl, ?array $languages = null, ?array $operationIds = null)
    {
        $this->registryUrl = $registryUrl;
        $this->languages = $languages;
        $this->operationIds = $operationIds;
    }
}