<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetManifestRequest
{
    /**
     *
     * @var string $namespaceName
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=namespace_name')]
    public string $namespaceName;

    /**
     *
     * @var string $organizationSlug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organization_slug')]
    public string $organizationSlug;

    /**
     * Tag or digest
     *
     * @var string $revisionReference
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=revision_reference')]
    public string $revisionReference;

    /**
     *
     * @var string $workspaceSlug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workspace_slug')]
    public string $workspaceSlug;

    /**
     * @param  string  $namespaceName
     * @param  string  $organizationSlug
     * @param  string  $revisionReference
     * @param  string  $workspaceSlug
     */
    public function __construct(string $namespaceName, string $organizationSlug, string $revisionReference, string $workspaceSlug)
    {
        $this->namespaceName = $namespaceName;
        $this->organizationSlug = $organizationSlug;
        $this->revisionReference = $revisionReference;
        $this->workspaceSlug = $workspaceSlug;
    }
}