<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetNamespacesRequest
{
    /**
     *
     * @var ?bool $isComposite
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=is_composite')]
    public ?bool $isComposite = null;

    /**
     * @param  ?bool  $isComposite
     */
    public function __construct(?bool $isComposite = null)
    {
        $this->isComposite = $isComposite;
    }
}