<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetOrganizationRequest
{
    /**
     * Unique identifier of the organization.
     *
     * @var string $organizationID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationID')]
    public string $organizationID;

    /**
     * @param  string  $organizationID
     */
    public function __construct(string $organizationID)
    {
        $this->organizationID = $organizationID;
    }
}