<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use \Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetWorkspaceEventsRequest
{
    /**
     * Filter to only return events corresponding to a particular gen_lock_id
     * 
     * @var ?string $generateGenLockId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=generate_gen_lock_id')]
    public ?string $generateGenLockId = null;
    
    /**
     * Unique identifier of the workspace.
     * 
     * @var ?string $workspaceID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workspaceID')]
    public ?string $workspaceID = null;
    
	public function __construct()
	{
		$this->generateGenLockId = null;
		$this->workspaceID = null;
	}
}
