<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GetWorkspaceAccessRequest
{
    /**
     * Unique identifier of the generation target.
     *
     * @var ?string $genLockId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=genLockId')]
    public ?string $genLockId = null;

    /**
     * Skip side-effects like incrementing metrics.
     *
     * @var ?bool $passive
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=passive')]
    public ?bool $passive = null;

    /**
     * The type of the generated target.
     *
     * @var ?string $targetType
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=targetType')]
    public ?string $targetType = null;

    /**
     * @param  ?string  $genLockId
     * @param  ?bool  $passive
     * @param  ?string  $targetType
     */
    public function __construct(?string $genLockId = null, ?bool $passive = null, ?string $targetType = null)
    {
        $this->genLockId = $genLockId;
        $this->passive = $passive;
        $this->targetType = $targetType;
    }
}