<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class GrantUserAccessToWorkspaceRequest
{
    /**
     * Email of the user to grant access to.
     *
     * @var string $email
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=email')]
    public string $email;

    /**
     * Unique identifier of the workspace.
     *
     * @var ?string $workspaceId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workspace_id')]
    public ?string $workspaceId = null;

    /**
     * @param  string  $email
     * @param  ?string  $workspaceId
     * @phpstan-pure
     */
    public function __construct(string $email, ?string $workspaceId = null)
    {
        $this->email = $email;
        $this->workspaceId = $workspaceId;
    }
}