<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use \Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class RunPluginRequest
{
    /**
     * The filter to apply to the query.
     * 
     * @var ?\Speakeasy\SpeakeasyClientSDK\Models\Shared\Filters $filters
     */
	#[SpeakeasyMetadata('queryParam:serialization=json,name=filters')]
    public ?\Speakeasy\SpeakeasyClientSDK\Models\Shared\Filters $filters = null;
    
    /**
     * The ID of the plugin to run.
     * 
     * @var string $pluginID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=pluginID')]
    public string $pluginID;
    
	public function __construct()
	{
		$this->filters = null;
		$this->pluginID = "";
	}
}
