<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;

use \Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class SearchWorkspaceEventsRequest
{
    /**
     * Unique identifier of the lint report digest.
     * 
     * @var ?string $lintReportDigest
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=lint_report_digest')]
    public ?string $lintReportDigest = null;
    
    /**
     * Unique identifier of the openapi diff report digest.
     * 
     * @var ?string $openapiDiffReportDigest
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=openapi_diff_report_digest')]
    public ?string $openapiDiffReportDigest = null;
    
    /**
     * Unique identifier of the source revision digest.
     * 
     * @var ?string $sourceRevisionDigest
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=source_revision_digest')]
    public ?string $sourceRevisionDigest = null;
    
    /**
     * Unique identifier of the workspace.
     * 
     * @var ?string $workspaceID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workspaceID')]
    public ?string $workspaceID = null;
    
	public function __construct()
	{
		$this->lintReportDigest = null;
		$this->openapiDiffReportDigest = null;
		$this->sourceRevisionDigest = null;
		$this->workspaceID = null;
	}
}
