<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Operations;


/** SetVisibilityRequestBody - Namespace visibility */
class SetVisibilityRequestBody
{
    /**
     *
     * @var bool $public
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public')]
    public bool $public;

    /**
     * @param  bool  $public
     */
    public function __construct(bool $public)
    {
        $this->public = $public;
    }
}