<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class AccessDetails
{
	#[\JMS\Serializer\Annotation\SerializedName('generation_allowed')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $generationAllowed;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	public function __construct()
	{
		$this->generationAllowed = false;
		$this->message = "";
	}
}
