<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


enum AccountType: string
{
    case Free = 'free';
    case ScaleUp = 'scale-up';
    case Enterprise = 'enterprise';
}
