<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** Annotations - Annotations */
class Annotations
{
    /**
     * The authors of the image
     *
     * @var ?string $orgOpencontainersImageAuthors
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.authors')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageAuthors = null;

    /**
     * The time the image was created
     *
     * @var ?string $orgOpencontainersImageCreated
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.created')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageCreated = null;

    /**
     * Human-readable description of the software packaged in the image
     *
     * @var ?string $orgOpencontainersImageDescription
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.description')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageDescription = null;

    /**
     * The documentation URL of the image
     *
     * @var ?string $orgOpencontainersImageDocumentation
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.documentation')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageDocumentation = null;

    /**
     *
     * @var ?string $orgOpencontainersImageLicenses
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.licenses')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageLicenses = null;

    /**
     * Name of the reference for a target
     *
     * @var ?string $orgOpencontainersImageRefName
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.ref.name')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageRefName = null;

    /**
     * Source control revision identifier
     *
     * @var ?string $orgOpencontainersImageRevision
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.revision')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageRevision = null;

    /**
     * The URL to get source code for building the image
     *
     * @var ?string $orgOpencontainersImageSource
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.source')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageSource = null;

    /**
     * Human-readable title of the image
     *
     * @var ?string $orgOpencontainersImageTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.title')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageTitle = null;

    /**
     * The URL of the image
     *
     * @var ?string $orgOpencontainersImageUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.url')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageUrl = null;

    /**
     * Name of the distributing entity, organization or individual.
     *
     * @var ?string $orgOpencontainersImageVendor
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.vendor')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageVendor = null;

    /**
     * The version of the packaged software
     *
     * @var ?string $orgOpencontainersImageVersion
     */
    #[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.version')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageVersion = null;

    /**
     * @param  ?string  $orgOpencontainersImageAuthors
     * @param  ?string  $orgOpencontainersImageCreated
     * @param  ?string  $orgOpencontainersImageDescription
     * @param  ?string  $orgOpencontainersImageDocumentation
     * @param  ?string  $orgOpencontainersImageLicenses
     * @param  ?string  $orgOpencontainersImageRefName
     * @param  ?string  $orgOpencontainersImageRevision
     * @param  ?string  $orgOpencontainersImageSource
     * @param  ?string  $orgOpencontainersImageTitle
     * @param  ?string  $orgOpencontainersImageUrl
     * @param  ?string  $orgOpencontainersImageVendor
     * @param  ?string  $orgOpencontainersImageVersion
     */
    public function __construct(?string $orgOpencontainersImageAuthors = null, ?string $orgOpencontainersImageCreated = null, ?string $orgOpencontainersImageDescription = null, ?string $orgOpencontainersImageDocumentation = null, ?string $orgOpencontainersImageLicenses = null, ?string $orgOpencontainersImageRefName = null, ?string $orgOpencontainersImageRevision = null, ?string $orgOpencontainersImageSource = null, ?string $orgOpencontainersImageTitle = null, ?string $orgOpencontainersImageUrl = null, ?string $orgOpencontainersImageVendor = null, ?string $orgOpencontainersImageVersion = null)
    {
        $this->orgOpencontainersImageAuthors = $orgOpencontainersImageAuthors;
        $this->orgOpencontainersImageCreated = $orgOpencontainersImageCreated;
        $this->orgOpencontainersImageDescription = $orgOpencontainersImageDescription;
        $this->orgOpencontainersImageDocumentation = $orgOpencontainersImageDocumentation;
        $this->orgOpencontainersImageLicenses = $orgOpencontainersImageLicenses;
        $this->orgOpencontainersImageRefName = $orgOpencontainersImageRefName;
        $this->orgOpencontainersImageRevision = $orgOpencontainersImageRevision;
        $this->orgOpencontainersImageSource = $orgOpencontainersImageSource;
        $this->orgOpencontainersImageTitle = $orgOpencontainersImageTitle;
        $this->orgOpencontainersImageUrl = $orgOpencontainersImageUrl;
        $this->orgOpencontainersImageVendor = $orgOpencontainersImageVendor;
        $this->orgOpencontainersImageVersion = $orgOpencontainersImageVersion;
    }
}