<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/**
 * Annotations - Annotations
 * 
 * @package Speakeasy\SpeakeasyClientSDK\Models\Shared
 * @access public
 */
class Annotations
{
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.authors')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageAuthors = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.base.digest')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageBaseDigest = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.base.name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageBaseName = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.created')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageCreated = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageDescription = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.documentation')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageDocumentation = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.licenses')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageLicenses = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.ref.name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageRefName = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.revision')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageRevision = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.source')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageSource = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageTitle = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageUrl = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.vendor')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageVendor = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('org.opencontainers.image.version')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orgOpencontainersImageVersion = null;
    
	public function __construct()
	{
		$this->orgOpencontainersImageAuthors = null;
		$this->orgOpencontainersImageBaseDigest = null;
		$this->orgOpencontainersImageBaseName = null;
		$this->orgOpencontainersImageCreated = null;
		$this->orgOpencontainersImageDescription = null;
		$this->orgOpencontainersImageDocumentation = null;
		$this->orgOpencontainersImageLicenses = null;
		$this->orgOpencontainersImageRefName = null;
		$this->orgOpencontainersImageRevision = null;
		$this->orgOpencontainersImageSource = null;
		$this->orgOpencontainersImageTitle = null;
		$this->orgOpencontainersImageUrl = null;
		$this->orgOpencontainersImageVendor = null;
		$this->orgOpencontainersImageVersion = null;
	}
}
