<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** Api - An Api is representation of a API (a collection of API Endpoints) within the Speakeasy Platform. */
class Api
{
    /**
     * The ID of this Api. This is a human-readable name (subject to change).
     *
     * @var string $apiId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('api_id')]
    public string $apiId;

    /**
     * Creation timestamp.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * A detailed description of the Api.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Determines if all the endpoints within the Api are found in the OpenAPI spec associated with the Api.
     *
     * @var ?bool $matched
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('matched')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $matched = null;

    /**
     * A set of values associated with a meta_data key. This field is only set on get requests.
     *
     * @var ?array<string, array<string>> $metaData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta_data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, array<string>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metaData = null;

    /**
     * Last update timestamp.
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public \DateTime $updatedAt;

    /**
     * The version ID of this Api. This is semantic version identifier.
     *
     * @var string $versionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version_id')]
    public string $versionId;

    /**
     * The workspace ID this Api belongs to.
     *
     * @var string $workspaceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workspace_id')]
    public string $workspaceId;

    /**
     * @param  string  $apiId
     * @param  \DateTime  $createdAt
     * @param  string  $description
     * @param  \DateTime  $updatedAt
     * @param  string  $versionId
     * @param  string  $workspaceId
     * @param  ?bool  $matched
     * @param  ?array<string, array<string>>  $metaData
     */
    public function __construct(string $apiId, \DateTime $createdAt, string $description, \DateTime $updatedAt, string $versionId, string $workspaceId, ?bool $matched = null, ?array $metaData = null)
    {
        $this->apiId = $apiId;
        $this->createdAt = $createdAt;
        $this->description = $description;
        $this->updatedAt = $updatedAt;
        $this->versionId = $versionId;
        $this->workspaceId = $workspaceId;
        $this->matched = $matched;
        $this->metaData = $metaData;
    }
}