<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** ApiInput - An Api is representation of a API (a collection of API Endpoints) within the Speakeasy Platform. */
class ApiInput
{
    /**
     * The ID of this Api. This is a human-readable name (subject to change).
     *
     * @var string $apiId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('api_id')]
    public string $apiId;

    /**
     * A detailed description of the Api.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * A set of values associated with a meta_data key. This field is only set on get requests.
     *
     * @var ?array<string, array<string>> $metaData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta_data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, array<string>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metaData = null;

    /**
     * The version ID of this Api. This is semantic version identifier.
     *
     * @var string $versionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version_id')]
    public string $versionId;

    /**
     * @param  string  $apiId
     * @param  string  $description
     * @param  string  $versionId
     * @param  ?array<string, array<string>>  $metaData
     */
    public function __construct(string $apiId, string $description, string $versionId, ?array $metaData = null)
    {
        $this->apiId = $apiId;
        $this->description = $description;
        $this->versionId = $versionId;
        $this->metaData = $metaData;
    }
}