<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class Auth
{
    /**
     *
     * @var string $header
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('header')]
    public string $header;

    /**
     *
     * @var string $secret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
    public string $secret;

    /**
     * @param  string  $header
     * @param  string  $secret
     * @phpstan-pure
     */
    public function __construct(string $header, string $secret)
    {
        $this->header = $header;
        $this->secret = $secret;
    }
}