<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** BoundedRequest - A BoundedRequest is a request that has been logged by the Speakeasy without the contents of the request. */
class BoundedRequest
{
    /**
     * The ID of the ApiEndpoint this request was made to.
     *
     * @var string $apiEndpointId
     */
    #[\JMS\Serializer\Annotation\SerializedName('api_endpoint_id')]
    public string $apiEndpointId;

    /**
     * The ID of the Api this request was made to.
     *
     * @var string $apiId
     */
    #[\JMS\Serializer\Annotation\SerializedName('api_id')]
    public string $apiId;

    /**
     * Creation timestamp.
     *
     * @var \DateTime $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The ID of the customer that made this request.
     *
     * @var string $customerId
     */
    #[\JMS\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     * The latency of the request.
     *
     * @var int $latency
     */
    #[\JMS\Serializer\Annotation\SerializedName('latency')]
    public int $latency;

    /**
     * Metadata associated with this request
     *
     * @var ?array<RequestMetadata> $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('array<\Speakeasy\SpeakeasyClientSDK\Models\Shared\RequestMetadata>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * HTTP verb.
     *
     * @var string $method
     */
    #[\JMS\Serializer\Annotation\SerializedName('method')]
    public string $method;

    /**
     * The path of the request.
     *
     * @var string $path
     */
    #[\JMS\Serializer\Annotation\SerializedName('path')]
    public string $path;

    /**
     * The time the request finished.
     *
     * @var \DateTime $requestFinishTime
     */
    #[\JMS\Serializer\Annotation\SerializedName('request_finish_time')]
    public \DateTime $requestFinishTime;

    /**
     * The ID of this request.
     *
     * @var string $requestId
     */
    #[\JMS\Serializer\Annotation\SerializedName('request_id')]
    public string $requestId;

    /**
     * The time the request was made.
     *
     * @var \DateTime $requestStartTime
     */
    #[\JMS\Serializer\Annotation\SerializedName('request_start_time')]
    public \DateTime $requestStartTime;

    /**
     * The status code of the request.
     *
     * @var int $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    public int $status;

    /**
     * The version ID of the Api this request was made to.
     *
     * @var string $versionId
     */
    #[\JMS\Serializer\Annotation\SerializedName('version_id')]
    public string $versionId;

    /**
     * The workspace ID this request was made to.
     *
     * @var string $workspaceId
     */
    #[\JMS\Serializer\Annotation\SerializedName('workspace_id')]
    public string $workspaceId;

    /**
     * @param  string  $apiEndpointId
     * @param  string  $apiId
     * @param  \DateTime  $createdAt
     * @param  string  $customerId
     * @param  int  $latency
     * @param  string  $method
     * @param  string  $path
     * @param  \DateTime  $requestFinishTime
     * @param  string  $requestId
     * @param  \DateTime  $requestStartTime
     * @param  int  $status
     * @param  string  $versionId
     * @param  string  $workspaceId
     * @param  ?array<RequestMetadata>  $metadata
     */
    public function __construct(string $apiEndpointId, string $apiId, \DateTime $createdAt, string $customerId, int $latency, string $method, string $path, \DateTime $requestFinishTime, string $requestId, \DateTime $requestStartTime, int $status, string $versionId, string $workspaceId, ?array $metadata = null)
    {
        $this->apiEndpointId = $apiEndpointId;
        $this->apiId = $apiId;
        $this->createdAt = $createdAt;
        $this->customerId = $customerId;
        $this->latency = $latency;
        $this->method = $method;
        $this->path = $path;
        $this->requestFinishTime = $requestFinishTime;
        $this->requestId = $requestId;
        $this->requestStartTime = $requestStartTime;
        $this->status = $status;
        $this->versionId = $versionId;
        $this->workspaceId = $workspaceId;
        $this->metadata = $metadata;
    }
}