<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;

use Speakeasy\SpeakeasyClientSDK\Utils\SpeakeasyMetadata;
class CodeSampleSchemaInput
{
    /**
     * A list of languages to generate code samples for
     *
     * @var array<string> $languages
     */
    #[SpeakeasyMetadata('multipartForm:name=languages')]
    public array $languages;

    /**
     * The OpenAPI file to be uploaded
     *
     * @var SchemaFile $schemaFile
     */
    #[SpeakeasyMetadata('multipartForm:file=true,name=schema_file')]
    public SchemaFile $schemaFile;

    /**
     * The name of the package
     *
     * @var ?string $packageName
     */
    #[SpeakeasyMetadata('multipartForm:name=package_name')]
    public ?string $packageName = null;

    /**
     * The SDK class name
     *
     * @var ?string $sdkClassName
     */
    #[SpeakeasyMetadata('multipartForm:name=sdk_class_name')]
    public ?string $sdkClassName = null;

    /**
     * @param  array<string>  $languages
     * @param  SchemaFile  $schemaFile
     * @param  ?string  $packageName
     * @param  ?string  $sdkClassName
     */
    public function __construct(array $languages, SchemaFile $schemaFile, ?string $packageName = null, ?string $sdkClassName = null)
    {
        $this->languages = $languages;
        $this->schemaFile = $schemaFile;
        $this->packageName = $packageName;
        $this->sdkClassName = $sdkClassName;
    }
}