<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class CompositeSpecMetadata
{
    /**
     * The subscription ID for the remote source subscription, if applicable. This indicates that the namespace is created by a remote source and thus is composite.
     *
     * @var string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_id')]
    public string $subscriptionId;

    /**
     *
     * @var RemoteSourceSubscriptionSettings $subscriptionSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\RemoteSourceSubscriptionSettings')]
    public RemoteSourceSubscriptionSettings $subscriptionSettings;

    /**
     * @param  string  $subscriptionId
     * @param  RemoteSourceSubscriptionSettings  $subscriptionSettings
     */
    public function __construct(string $subscriptionId, RemoteSourceSubscriptionSettings $subscriptionSettings)
    {
        $this->subscriptionId = $subscriptionId;
        $this->subscriptionSettings = $subscriptionSettings;
    }
}