<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


enum DepthStyle: string
{
    case Original = 'original';
    case Flat = 'flat';
    case Nested = 'nested';
    case Deep = 'deep';
}
