<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** FeatureFlag - A feature flag is a key-value pair that can be used to enable or disable features. */
class FeatureFlag
{
    #[\JMS\Serializer\Annotation\SerializedName('feature_flag')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $featureFlag;

    #[\JMS\Serializer\Annotation\SerializedName('trial_ends_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $trialEndsAt = null;

    public function __construct()
    {
        $this->featureFlag = '';
        $this->trialEndsAt = null;
    }
}