<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** Bump type of the lock file (calculated semver delta, or a custom change (manual release)) */
enum GenerateBumpType: string
{
    case Major = 'major';
    case Minor = 'minor';
    case Patch = 'patch';
    case Custom = 'custom';
    case None = 'none';
}
