<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class GetRevisionsResponse
{
    /**
     *
     * @var bool $isCompositeSpec
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_composite_spec')]
    public bool $isCompositeSpec;

    /**
     * $items
     *
     * @var array<Revision> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Speakeasy\SpeakeasyClientSDK\Models\Shared\Revision>')]
    public array $items;

    /**
     *
     * @var string $nextPageToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('next_page_token')]
    public string $nextPageToken;

    /**
     *
     * @var bool $public
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public')]
    public bool $public;

    /**
     * @param  bool  $isCompositeSpec
     * @param  array<Revision>  $items
     * @param  string  $nextPageToken
     * @param  bool  $public
     */
    public function __construct(bool $isCompositeSpec, array $items, string $nextPageToken, bool $public)
    {
        $this->isCompositeSpec = $isCompositeSpec;
        $this->items = $items;
        $this->nextPageToken = $nextPageToken;
        $this->public = $public;
    }
}