<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class GetTagsResponse
{
    /**
     * $items
     *
     * @var array<Tag> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Speakeasy\SpeakeasyClientSDK\Models\Shared\Tag>')]
    public array $items;

    /**
     * @param  array<Tag>  $items
     */
    public function __construct(array $items)
    {
        $this->items = $items;
    }
}