<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** GithubPublishingPRResponse - Open generation PRs pending publishing */
class GithubPublishingPRResponse
{
    /**
     *
     * @var ?string $generationPullRequest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('generation_pull_request')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $generationPullRequest = null;

    /**
     *
     * @var ?string $pendingVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pending_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pendingVersion = null;

    /**
     * @param  ?string  $generationPullRequest
     * @param  ?string  $pendingVersion
     */
    public function __construct(?string $generationPullRequest = null, ?string $pendingVersion = null)
    {
        $this->generationPullRequest = $generationPullRequest;
        $this->pendingVersion = $pendingVersion;
    }
}