<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** GithubGetActionResponse - response to a getting the latest action run on a GitHub request */
class GithubGetActionResponse
{
    /**
     * The status of the latest action run if available
     *
     * @var ?string $runStatus
     */
    #[\JMS\Serializer\Annotation\SerializedName('run_status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $runStatus = null;

    /**
     * The URL for latest action run if available
     *
     * @var ?string $runUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('run_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $runUrl = null;

    public function __construct()
    {
        $this->runStatus = null;
        $this->runUrl = null;
    }
}