<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** GithubMissingPublishingSecretsResponse - A valid response containing MISSING publishing secret keys for a github target */
class GithubMissingPublishingSecretsResponse
{
    /**
     * $missingSecrets
     *
     * @var ?array<string> $missingSecrets
     */
    #[\JMS\Serializer\Annotation\SerializedName('missing_secrets')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $missingSecrets = null;

    public function __construct()
    {
        $this->missingSecrets = null;
    }
}