<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** GithubConfigureCodeSamplesResponse - A response to configure GitHub code samples */
class GithubConfigureCodeSamplesResponse
{
    /**
     * The URL of the code sample overlay registry
     *
     * @var string $codeSampleOverlayRegistryURL
     */
    #[\JMS\Serializer\Annotation\SerializedName('codeSampleOverlayRegistryURL')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $codeSampleOverlayRegistryURL;

    /**
     * The ID of the GitHub action that was dispatched
     *
     * @var ?string $ghActionID
     */
    #[\JMS\Serializer\Annotation\SerializedName('ghActionID')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ghActionID = null;

    /**
     * A document referenced by a workflow
     *
     * @var \Speakeasy\SpeakeasyClientSDK\Models\Shared\WorkflowDocument $source
     */
    #[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('Speakeasy\SpeakeasyClientSDK\Models\Shared\WorkflowDocument')]
    public WorkflowDocument $source;

    public function __construct()
    {
        $this->codeSampleOverlayRegistryURL = '';
        $this->ghActionID = null;
        $this->source = new \Speakeasy\SpeakeasyClientSDK\Models\Shared\WorkflowDocument();
    }
}