<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** GithubConfigureCodeSamplesRequest - A request to configure GitHub code samples */
class GithubConfigureCodeSamplesRequest
{
    /**
     * The GitHub organization name
     *
     * @var string $org
     */
    #[\JMS\Serializer\Annotation\SerializedName('org')]
    public string $org;

    /**
     * The GitHub repository name
     *
     * @var string $repo
     */
    #[\JMS\Serializer\Annotation\SerializedName('repo')]
    public string $repo;

    /**
     * The target name for the code samples
     *
     * @var string $targetName
     */
    #[\JMS\Serializer\Annotation\SerializedName('targetName')]
    public string $targetName;

    /**
     * @param  ?string  $org
     * @param  ?string  $repo
     * @param  ?string  $targetName
     */
    public function __construct(?string $org = null, ?string $repo = null, ?string $targetName = null)
    {
        $this->org = $org;
        $this->repo = $repo;
        $this->targetName = $targetName;
    }
}