<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** Type of interaction. */
enum InteractionType: string
{
    case CiExec = 'CI_EXEC';
    case CliExec = 'CLI_EXEC';
    case Lint = 'LINT';
    case OpenapiDiff = 'OPENAPI_DIFF';
    case TargetGenerate = 'TARGET_GENERATE';
    case Tombstone = 'TOMBSTONE';
    case Authenticate = 'AUTHENTICATE';
    case Quickstart = 'QUICKSTART';
    case Run = 'RUN';
    case Configure = 'CONFIGURE';
    case Publish = 'PUBLISH';
}
