<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** NamespaceT - A namespace contains many revisions. */
class NamespaceT
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * {organization_slug}/{workspace_slug}/{namespace_name}
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * A human-readable name for the namespace.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public \DateTime $updatedAt;

    /**
     *
     * @var ?\DateTime $archivedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('archived_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $archivedAt = null;

    /**
     *
     * @var ?CompositeSpecMetadata $compositeSpecMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('composite_spec_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\CompositeSpecMetadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CompositeSpecMetadata $compositeSpecMetadata = null;

    /**
     *
     * @var ?RevisionContentsMetadata $latestRevisionMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('latest_revision_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\RevisionContentsMetadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RevisionContentsMetadata $latestRevisionMetadata = null;

    /**
     * Indicates whether the namespace is publicly accessible
     *
     * @var ?bool $public
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $public = null;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  string  $name
     * @param  \DateTime  $updatedAt
     * @param  ?\DateTime  $archivedAt
     * @param  ?CompositeSpecMetadata  $compositeSpecMetadata
     * @param  ?RevisionContentsMetadata  $latestRevisionMetadata
     * @param  ?bool  $public
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $id, string $name, \DateTime $updatedAt, ?\DateTime $archivedAt = null, ?CompositeSpecMetadata $compositeSpecMetadata = null, ?RevisionContentsMetadata $latestRevisionMetadata = null, ?bool $public = null)
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->name = $name;
        $this->updatedAt = $updatedAt;
        $this->archivedAt = $archivedAt;
        $this->compositeSpecMetadata = $compositeSpecMetadata;
        $this->latestRevisionMetadata = $latestRevisionMetadata;
        $this->public = $public;
    }
}