<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class OASSummary
{
    /**
     *
     * @var OASInfo $info
     */
    #[\JMS\Serializer\Annotation\SerializedName('info')]
    #[\JMS\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\OASInfo')]
    public OASInfo $info;

    /**
     * $operations
     *
     * @var array<OASOperation> $operations
     */
    #[\JMS\Serializer\Annotation\SerializedName('operations')]
    #[\JMS\Serializer\Annotation\Type('array<\Speakeasy\SpeakeasyClientSDK\Models\Shared\OASOperation>')]
    public array $operations;

    /**
     * @param  ?OASInfo  $info
     * @param  ?array<OASOperation>  $operations
     */
    public function __construct(?OASInfo $info = null, ?array $operations = null)
    {
        $this->info = $info;
        $this->operations = $operations;
    }
}