<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** OrganizationUsageResponse - A billing summary of organization usage */
class OrganizationUsageResponse
{
    /**
     * List of allowed languages
     *
     * @var array<string> $allowedLanguages
     */
    #[\JMS\Serializer\Annotation\SerializedName('allowed_languages')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $allowedLanguages;

    /**
     * Expiry date of the free trial, will be null if no trial
     *
     * @var ?\DateTime $freeTrialExpiry
     */
    #[\JMS\Serializer\Annotation\SerializedName('free_trial_expiry')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $freeTrialExpiry = null;

    /**
     * Total number of allowed languages, -1 if unlimited
     *
     * @var int $totalAllowedLanguages
     */
    #[\JMS\Serializer\Annotation\SerializedName('total_allowed_languages')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalAllowedLanguages;

    /**
     * $usage
     *
     * @var array<\Speakeasy\SpeakeasyClientSDK\Models\Shared\OrganizationUsage> $usage
     */
    #[\JMS\Serializer\Annotation\SerializedName('usage')]
    #[\JMS\Serializer\Annotation\Type('array<Speakeasy\SpeakeasyClientSDK\Models\Shared\OrganizationUsage>')]
    public array $usage;

    public function __construct()
    {
        $this->allowedLanguages = [];
        $this->freeTrialExpiry = null;
        $this->totalAllowedLanguages = 0;
        $this->usage = [];
    }
}