<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** Organization - A speakeasy organization */
class Organization
{
    /**
     *
     * @var AccountType $accountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\AccountType')]
    public AccountType $accountType;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var ?\DateTime $freeTrialExpiry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('free_trial_expiry')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $freeTrialExpiry = null;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ?bool $internal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('internal')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $internal = null;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     *
     * @var bool $telemetryDisabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('telemetry_disabled')]
    public bool $telemetryDisabled;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public \DateTime $updatedAt;

    /**
     * @param  AccountType  $accountType
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  string  $name
     * @param  string  $slug
     * @param  bool  $telemetryDisabled
     * @param  \DateTime  $updatedAt
     * @param  ?bool  $internal
     * @param  ?\DateTime  $freeTrialExpiry
     */
    public function __construct(AccountType $accountType, \DateTime $createdAt, string $id, string $name, string $slug, bool $telemetryDisabled, \DateTime $updatedAt, ?bool $internal = null, ?\DateTime $freeTrialExpiry = null)
    {
        $this->accountType = $accountType;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->name = $name;
        $this->slug = $slug;
        $this->telemetryDisabled = $telemetryDisabled;
        $this->updatedAt = $updatedAt;
        $this->internal = $internal;
        $this->freeTrialExpiry = $freeTrialExpiry;
    }
}