<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class PreflightRequest
{
    #[\JMS\Serializer\Annotation\SerializedName('namespace_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $namespaceName;

    public function __construct()
    {
        $this->namespaceName = '';
    }
}