<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** PreflightToken - A PreflightToken is a token that allows access to the OCI distribution endpoints. */
class PreflightToken
{
    /**
     *
     * @var ?string $authToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('auth_token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authToken = null;

    /**
     * @param  ?string  $authToken
     * @phpstan-pure
     */
    public function __construct(?string $authToken = null)
    {
        $this->authToken = $authToken;
    }
}