<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** PreflightToken - A PreflightToken is a token that allows access to the OCI distribution endpoints. */
class PreflightToken
{
    #[\JMS\Serializer\Annotation\SerializedName('auth_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $authToken = null;

    public function __construct()
    {
        $this->authToken = null;
    }
}