<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class Secrets
{
    /**
     *
     * @var bool $apiKeyConfigured
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('api_key_configured')]
    public bool $apiKeyConfigured;

    /**
     *
     * @var bool $publishingSecretsConfigured
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('publishing_secrets_configured')]
    public bool $publishingSecretsConfigured;

    /**
     * @param  bool  $apiKeyConfigured
     * @param  bool  $publishingSecretsConfigured
     */
    public function __construct(bool $apiKeyConfigured, bool $publishingSecretsConfigured)
    {
        $this->apiKeyConfigured = $apiKeyConfigured;
        $this->publishingSecretsConfigured = $publishingSecretsConfigured;
    }
}