<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


enum SuggestRequestBodySuggestionType: string
{
    case MethodNames = 'method-names';
    case DiagnosticsOnly = 'diagnostics-only';
}
