<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class SuggestRequestBody
{
    /**
     * $diagnostics
     *
     * @var array<Diagnostic> $diagnostics
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('diagnostics')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Speakeasy\SpeakeasyClientSDK\Models\Shared\Diagnostic>')]
    public array $diagnostics;

    /**
     *
     * @var OASSummary $oasSummary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('oas_summary')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\OASSummary')]
    public OASSummary $oasSummary;

    /**
     *
     * @var SuggestRequestBodySuggestionType $suggestionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('suggestion_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\SuggestRequestBodySuggestionType')]
    public SuggestRequestBodySuggestionType $suggestionType;

    /**
     * @param  array<Diagnostic>  $diagnostics
     * @param  OASSummary  $oasSummary
     * @param  SuggestRequestBodySuggestionType  $suggestionType
     */
    public function __construct(array $diagnostics, OASSummary $oasSummary, SuggestRequestBodySuggestionType $suggestionType)
    {
        $this->diagnostics = $diagnostics;
        $this->oasSummary = $oasSummary;
        $this->suggestionType = $suggestionType;
    }
}