<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class UsageSnippet
{
    /**
     * The code snippet
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     * The language of the snippet
     *
     * @var string $language
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('language')]
    public string $language;

    /**
     * The operation ID for the snippet
     *
     * @var string $operationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operationId')]
    public string $operationId;

    /**
     * @param  string  $code
     * @param  string  $language
     * @param  string  $operationId
     */
    public function __construct(string $code, string $language, string $operationId)
    {
        $this->code = $code;
        $this->language = $language;
        $this->operationId = $operationId;
    }
}