<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


class WorkspaceSettings
{
    /**
     *
     * @var ?string $webhookUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('webhook_url')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $webhookUrl = null;

    /**
     *
     * @var string $workspaceId
     */
    #[\JMS\Serializer\Annotation\SerializedName('workspace_id')]
    public string $workspaceId;

    /**
     * @param  string  $workspaceId
     * @param  ?string  $webhookUrl
     */
    public function __construct(string $workspaceId, ?string $webhookUrl = null)
    {
        $this->workspaceId = $workspaceId;
        $this->webhookUrl = $webhookUrl;
    }
}