<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** WorkspaceAndOrganization - A workspace and organization */
class WorkspaceAndOrganization
{
    /**
     * A speakeasy organization
     *
     * @var Organization $organization
     */
    #[\JMS\Serializer\Annotation\SerializedName('organization')]
    #[\JMS\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\Organization')]
    public Organization $organization;

    /**
     * A speakeasy workspace
     *
     * @var Workspace $workspace
     */
    #[\JMS\Serializer\Annotation\SerializedName('workspace')]
    #[\JMS\Serializer\Annotation\Type('\Speakeasy\SpeakeasyClientSDK\Models\Shared\Workspace')]
    public Workspace $workspace;

    /**
     * @param  Organization  $organization
     * @param  Workspace  $workspace
     */
    public function __construct(Organization $organization, Workspace $workspace)
    {
        $this->organization = $organization;
        $this->workspace = $workspace;
    }
}