<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK\Models\Shared;


/** WorkspaceToken - A workspace token */
class WorkspaceToken
{
    /**
     *
     * @var string $alg
     */
    #[\JMS\Serializer\Annotation\SerializedName('alg')]
    public string $alg;

    /**
     *
     * @var string $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_at')]
    public string $createdAt;

    /**
     *
     * @var ?string $createdBy
     */
    #[\JMS\Serializer\Annotation\SerializedName('created_by')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $createdBy = null;

    /**
     *
     * @var ?string $email
     */
    #[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     *
     * @var ?string $lastUsed
     */
    #[\JMS\Serializer\Annotation\SerializedName('last_used')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $lastUsed = null;

    /**
     *
     * @var string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var ?string $workspaceId
     */
    #[\JMS\Serializer\Annotation\SerializedName('workspace_id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $workspaceId = null;

    /**
     * @param  string  $alg
     * @param  string  $createdAt
     * @param  string  $id
     * @param  string  $key
     * @param  string  $name
     * @param  ?string  $workspaceId
     * @param  ?string  $createdBy
     * @param  ?string  $email
     * @param  ?string  $lastUsed
     */
    public function __construct(string $alg, string $createdAt, string $id, string $key, string $name, ?string $workspaceId = null, ?string $createdBy = null, ?string $email = null, ?string $lastUsed = null)
    {
        $this->alg = $alg;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->key = $key;
        $this->name = $name;
        $this->workspaceId = $workspaceId;
        $this->createdBy = $createdBy;
        $this->email = $email;
        $this->lastUsed = $lastUsed;
    }
}