<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Speakeasy\SpeakeasyClientSDK;

class Suggest
{
    private SDKConfiguration $sdkConfiguration;

    /**
     * @param  SDKConfiguration  $sdkConfig
     */
    public function __construct(SDKConfiguration $sdkConfig)
    {
        $this->sdkConfiguration = $sdkConfig;
    }

    /**
     * Generate operation ID suggestions.
     *
     * Get suggestions from an LLM model for improving the operationIDs in the provided schema.
     *
     * @param  \Speakeasy\SpeakeasyClientSDK\Models\Operations\SuggestOperationIDsRequestBody  $request
     * @return \Speakeasy\SpeakeasyClientSDK\Models\Operations\SuggestOperationIDsResponse
     */
    public function suggestOperationIDs(
        \Speakeasy\SpeakeasyClientSDK\Models\Operations\SuggestOperationIDsRequestBody $request,
    ): \Speakeasy\SpeakeasyClientSDK\Models\Operations\SuggestOperationIDsResponse {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/v1/suggest/operation_ids');
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, 'request', 'multipart');
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;

        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \Speakeasy\SpeakeasyClientSDK\Models\Operations\SuggestOperationIDsResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->suggestion = $serializer->deserialize((string) $httpResponse->getBody(), 'Speakeasy\SpeakeasyClientSDK\Models\Operations\SuggestOperationIDsSuggestion', 'json');
            }
        }

        return $response;
    }
}